---
- hosts: all
  become: yes
  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: /etc/gdm3/custom.conf
        dest: /etc/gdm3/custom.conf.bak
    - name: Enable autologin
      replace:
        path: /etc/gdm3/custom.conf
        regexp: '#  AutomaticLoginEnable = true'
        replace: 'AutomaticLoginEnable = true'
        backup: yes
    - name: Change login user to vagrant
      replace:
        path: /etc/gdm3/custom.conf
        regexp: '#  AutomaticLogin = user1'
        replace: 'AutomaticLogin = vagrant'
        backup: yes